Repository AGH-Wstep-do-Informatyki-2022-2023/Grupa-2, pull requests merged in 2022-12, with the labels that each got.

#10 Przykładowa grafika
  kotek.jpg
Labels: help wanted

#12 Delete Felis_catus-cat_on_snow.jpg
  Felis_catus-cat_on_snow.jpg
Labels: good first issue

#13 Pies
  pies.jpg
Labels: documentation

#14 Add files via upload
  Felis_catus-cat_on_snow.jpg
Labels: invalid

#16 Add files via upload
  kod stan na 29.12.2022
  pacman.jpg
Labels: wontfix
